### ISSUE TITLE
A memory leak on Windows Server 2008 R2 

### ISSUE THREAD

**Issue by maraev** [CryptonZylog/carbonator#22]
Hello, 
First of all, thanx for your good application. It works fine on my Win7 system.
Second, I've tested it on my Win Server 2008 and watching that the operation memory was filled during some days. 
![carbonator1](https://cloud.githubusercontent.com/assets/3273410/20301607/041364d4-ab35-11e6-9286-65fbab0405ea.jpg)
 How can I fix it?

**Comment by CryptonZylog** [comment]
Do you know which build of Carbonator you are running?

1. Download and unpack [CLR profiler](https://www.microsoft.com/en-us/download/details.aspx?id=16273)
2. Run CLR profiler (Binaries\64\CLRProfiler.exe)
3. Attach to process (enter PID of the Carbonator process)
4. Click "Show Heap Now"
5. Expand the heap window and try to take a screenshot (play with Scale/Detail radio buttons)
6. Post screenshot here

Thanks!

**Comment by maraev** [comment]
Hello!
Unfortunattelly, I'm not expert in CLR Profiler debuging. I've stuck on step 3 with getting message form CLRProfiler like
![er1](https://cloud.githubusercontent.com/assets/3273410/20475390/ab35689c-afdc-11e6-8ce1-41c5ddf88dd8.jpg) 
Event 1022 .Net Runtime
.NET Runtime version 4.0.30319.1026 - Loading profiler failed.  The profiler COM object was instantiated, but the profiler failed during its initialization callback.  Profiler CLSID: '{8C29BC4E-1F57-461A-9B51-1200C32E6F1F}'.  HRESULT: 0x80131376.  Process ID (decimal): 1184.  Message ID: [0x2505].
Also just to clarify  I'm getting error log when I try to start the service Carbonator v.2.0 
```
Service cannot be started. System.Configuration.ConfigurationErrorsException: Unrecognized attribute 'logLevel'. Note that attribute names are case-sensitive. (C:\Program Files\Carbonator\Crypton.Carbonator.exe.Config line 13)
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean request...
```

therefore I'm testing on v.1.5

**Comment by CryptonZylog** [comment]
Try [turning off concurrent GC](http://stackoverflow.com/questions/21663554/how-do-i-turn-off-concurrent-garbage-collection) (step 1 in message box). You will have to restart Carbonator for this to take effect.

Version 2.0 was recently updated, try the latest build. As for configuration errors you are seeing in that, note that 'logLevel' is deprecated setting and needs to be *removed* from your config.

**Comment by maraev** [comment]
Hi!
I'm not sure about accuracy the following screen but still
![carbmemleak](https://cloud.githubusercontent.com/assets/3273410/20591820/8adae44e-b23b-11e6-9ceb-8c134c2e40d0.jpg)
I haven't done attach PID number, just run as a Profile Service
I'm still have the issues with carbonator 2.0. Despite I've fixed some lines in config file, service haven't started. So I've tested on v.1.5 
 Please see my config as well 

[Crypton.Carbonator.exe.config.zip](https://github.com/CryptonZylog/carbonator/files/610856/Crypton.Carbonator.exe.config.zip)

**Comment by maraev** [comment]
<root> :	 794 kB    (100.00%)
  Previous allocations (newest to oldest):  799 kB    (100.53%),   820 kB    (103.23%),   813 kB    (102.29%),  
 Handle, Pinning <root>->Handle, Pinning->(System.Object []):	 769 kB    (96.78%)
   Previous allocations (newest to oldest):  773 kB    (97.30%),   772 kB    (97.19%),   769 kB    (96.78%),  
 Handle <root>->Handle->(System.SharedStatics):	  18 kB    (2.22%)
   Previous allocations (newest to oldest):   18 kB    (2.22%),    18 kB    (2.22%),    18 kB    (2.22%),  
  System.Object [] Handle, Pinning->System.Object []->(System.Collections.Concurrent.BlockingCollection<T>,System.Net.Sockets.TcpClient,System.Threading.Timer,...):	 647 kB    (81.48%)  (1 object,   16 kB    (2.01%))
    Previous allocations (newest to oldest):  651 kB    (82.00%),   651 kB    (81.89%),   647 kB    (81.48%),  
  System.Object [] Handle, Pinning->System.Object []->(System.DirectoryServices.ActiveDirectory.LoadLibrarySafeHandle,System.Security.PermissionSet,System.String,...):	  45 kB    (5.63%)  (1 object,   32 kB    (4.02%))
    Previous allocations (newest to oldest):   45 kB    (5.63%),    45 kB    (5.63%),    45 kB    (5.63%),  
  System.Object [] Handle, Pinning->System.Object []->(System.Char [],System.CultureAwareComparer,System.String,...):	  37 kB    (4.65%)  (1 object,  8.0 kB    (1.01%))
    Previous allocations (newest to oldest):   37 kB    (4.65%),    37 kB    (4.65%),    37 kB    (4.65%),  
  System.Object [] Handle, Pinning->System.Object []->(System.RuntimeType,System.String):	  35 kB    (4.46%)  (1 object,  8.0 kB    (1.01%))
    Previous allocations (newest to oldest):   35 kB    (4.46%),    35 kB    (4.46%),    35 kB    (4.46%),  
  System.SharedStatics Handle->System.SharedStatics->(System.Security.Util.Tokenizer.StringMaker):	  18 kB    (2.22%)  (1 object,   48 bytes (0.01%))
    Previous allocations (newest to oldest):   18 kB    (2.22%),    18 kB    (2.22%),    18 kB    (2.22%),  
   System.Collections.Hashtable System.Object []->System.Collections.Hashtable->(System.Collections.Hashtable.bucket []):	 369 kB    (46.40%)  (9 objects,  792 bytes (0.10%))
     Previous allocations (newest to oldest):  369 kB    (46.40%),   369 kB    (46.40%),   369 kB    (46.40%),  
   System.Diagnostics.SystemDiagnosticsSection System.Object []->System.Diagnostics.SystemDiagnosticsSection->(System.Configuration.ConfigurationValues,System.Configuration.RuntimeConfigurationRecord):	  82 kB    (10.35%)  (1 object,  120 bytes (0.01%))
     Previous allocations (newest to oldest):   82 kB    (10.35%),    82 kB    (10.35%),    82 kB    (10.35%),  
   Crypton.Carbonator.Config.CarbonatorSection System.Object []->Crypton.Carbonator.Config.CarbonatorSection->(System.Configuration.ConfigurationElementProperty,System.Configuration.ConfigurationValues,System.Configuration.SectionInformation):	  57 kB    (7.17%)  (1 object,  120 bytes (0.01%))
     Previous allocations (newest to oldest):   57 kB    (7.17%),    57 kB    (7.17%),    57 kB    (7.17%),  
   System.Collections.Generic.LinkedList<T> System.Object []->System.Collections.Generic.LinkedList<T>->(System.Collections.Generic.LinkedListNode<T>):	  32 kB    (4.02%)  (1 object,   48 bytes (0.01%))
     Previous allocations (newest to oldest):   32 kB    (4.02%),    32 kB    (4.02%),    32 kB    (4.02%),  
   System.Collections.Generic.List<T> System.Object []->System.Collections.Generic.List<T>->(Crypton.Carbonator.CounterWatcher []):	  24 kB    (2.98%)  (1 object,   40 bytes (0.00%))
     Previous allocations (newest to oldest):   24 kB    (2.98%),    24 kB    (2.98%),    24 kB    (2.98%),  
   System.Security.Util.Tokenizer.StringMaker System.SharedStatics->System.Security.Util.Tokenizer.StringMaker->(System.String []):	  18 kB    (2.21%)  (1 object,   56 bytes (0.01%))
     Previous allocations (newest to oldest):   18 kB    (2.21%),    18 kB    (2.21%),    18 kB    (2.21%),  
   System.Collections.Generic.Dictionary<T,U> System.Object []->System.Collections.Generic.Dictionary<T,U>->(System.Collections.Generic.GenericEqualityComparer<T>,System.Int32 []):	  11 kB    (1.41%)  (4 objects,  352 bytes (0.04%))
     Previous allocations (newest to oldest):   11 kB    (1.41%),    11 kB    (1.41%),    11 kB    (1.41%),  
   System.Collections.Concurrent.BlockingCollection<T> System.Object []->System.Collections.Concurrent.BlockingCollection<T>->(System.Collections.Concurrent.ConcurrentQueue<T>,System.Threading.CancellationTokenSource,System.Threading.SemaphoreSlim):	 8.3 kB    (1.04%)  (1 object,   72 bytes (0.01%))
     Previous allocations (newest to oldest):   12 kB    (1.56%),    12 kB    (1.45%),   8.3 kB    (1.04%),  
    System.Configuration.RuntimeConfigurationRecord System.Diagnostics.SystemDiagnosticsSection->System.Configuration.RuntimeConfigurationRecord->(System.Configuration.Internal.InternalConfigRoot,System.Configuration.RuntimeConfigurationRecord,System.String,...):	  78 kB    (9.85%)  (1 object,  144 bytes (0.02%))
      Previous allocations (newest to oldest):   78 kB    (9.85%),    78 kB    (9.85%),    78 kB    (9.85%),  
    System.Configuration.ConfigurationValues Crypton.Carbonator.Config.CarbonatorSection->System.Configuration.ConfigurationValues->(System.Collections.ArrayList,System.Collections.Hashtable):	  41 kB    (5.14%)  (1 object,   88 bytes (0.01%))
      Previous allocations (newest to oldest):   41 kB    (5.14%),    41 kB    (5.14%),    41 kB    (5.14%),  
    System.Collections.Generic.LinkedListNode<T> System.Collections.Generic.LinkedList<T>->System.Collections.Generic.LinkedListNode<T>->(System.Collections.Generic.LinkedList<T>,System.Collections.Generic.LinkedListNode<T>):	  32 kB    (4.02%)  (1 object,   48 bytes (0.01%))
      Previous allocations (newest to oldest):   32 kB    (4.02%),    32 kB    (4.02%),    32 kB    (4.02%),  
    Crypton.Carbonator.CounterWatcher [] System.Collections.Generic.List<T>->Crypton.Carbonator.CounterWatcher []->(Crypton.Carbonator.CounterWatcher):	  24 kB    (2.98%)  (1 object,  288 bytes (0.04%))
      Previous allocations (newest to oldest):   24 kB    (2.98%),    24 kB    (2.98%),    24 kB    (2.98%),  
    System.String [] System.Security.Util.Tokenizer.StringMaker->System.String []->(System.String):	  17 kB    (2.08%)  (1 object,   16 kB    (2.02%))
      Previous allocations (newest to oldest):   17 kB    (2.08%),    17 kB    (2.08%),    17 kB    (2.08%),  
    System.Configuration.RuntimeConfigurationRecord Crypton.Carbonator.Config.CarbonatorSection->System.Configuration.RuntimeConfigurationRecord->(System.Configuration.Internal.InternalConfigRoot,System.Configuration.RuntimeConfigurationRecord,System.String,...):	  16 kB    (1.97%)  (1 object,  144 bytes (0.02%))
      Previous allocations (newest to oldest):   16 kB    (1.97%),    16 kB    (1.97%),    16 kB    (1.97%),  
     System.Collections.Generic.LinkedListNode<T> System.Collections.Generic.LinkedListNode<T>->System.Collections.Generic.LinkedListNode<T>->(System.Collections.Generic.LinkedList<T>,System.Collections.Generic.LinkedListNode<T>):	  30 kB    (3.73%)  (14 objects,  672 bytes (0.08%))
       Previous allocations (newest to oldest):   30 kB    (3.73%),    30 kB    (3.73%),    30 kB    (3.73%),  
     Crypton.Carbonator.CounterWatcher Crypton.Carbonator.CounterWatcher []->Crypton.Carbonator.CounterWatcher->(System.Collections.Generic.Dictionary<T,U>,System.String):	  23 kB    (2.94%)  (25 objects,  1.6 kB    (0.20%))
       Previous allocations (newest to oldest):   23 kB    (2.94%),    23 kB    (2.94%),    23 kB    (2.94%),  
      System.Collections.Hashtable System.Configuration.RuntimeConfigurationRecord->System.Collections.Hashtable->(System.Collections.Hashtable.bucket []):	  93 kB    (11.73%)  (9 objects,  792 bytes (0.10%))
        Previous allocations (newest to oldest):   93 kB    (11.73%),    93 kB    (11.73%),    93 kB    (11.73%),  
      System.Text.RegularExpressions.CachedCodeEntry System.Collections.Generic.LinkedListNode<T>->System.Text.RegularExpressions.CachedCodeEntry->(System.String,System.Text.RegularExpressions.ExclusiveReference):	  31 kB    (3.93%)  (15 objects,  1.3 kB    (0.16%))
        Previous allocations (newest to oldest):   31 kB    (3.93%),    31 kB    (3.93%),    31 kB    (3.93%),  
      System.Collections.Generic.List<T> Crypton.Carbonator.CounterWatcher->System.Collections.Generic.List<T>->(System.Diagnostics.PerformanceCounter []):	  13 kB    (1.65%)  (25 objects, 1000 bytes (0.12%))
        Previous allocations (newest to oldest):   13 kB    (1.65%),    13 kB    (1.65%),    13 kB    (1.65%),  
      System.Collections.Generic.Dictionary<T,U>.Entry [] System.Collections.Generic.Dictionary<T,U>->System.Collections.Generic.Dictionary<T,U>.Entry []->(System.String):	  11 kB    (1.39%)  (5 objects,  7.2 kB    (0.91%))
        Previous allocations (newest to oldest):   11 kB    (1.39%),    11 kB    (1.39%),    11 kB    (1.39%),  
       System.Collections.Hashtable.bucket [] System.Collections.Hashtable->System.Collections.Hashtable.bucket []->(System.String):	 466 kB    (58.71%)  (48 objects,   20 kB    (2.47%))
         Previous allocations (newest to oldest):  466 kB    (58.71%),   476 kB    (59.96%),   474 kB    (59.71%),  
       System.Text.RegularExpressions.ExclusiveReference System.Text.RegularExpressions.CachedCodeEntry->System.Text.RegularExpressions.ExclusiveReference->(System.Text.RegularExpressions.RegexInterpreter):	  15 kB    (1.92%)  (15 objects,  600 bytes (0.07%))
         Previous allocations (newest to oldest):   15 kB    (1.92%),    15 kB    (1.92%),    15 kB    (1.92%),  
       System.Text.RegularExpressions.RegexCode System.Text.RegularExpressions.CachedCodeEntry->System.Text.RegularExpressions.RegexCode->(System.Int32 [],System.Text.RegularExpressions.RegexPrefix):	  13 kB    (1.59%)  (15 objects,  1.1 kB    (0.13%))
         Previous allocations (newest to oldest):   13 kB    (1.59%),    13 kB    (1.59%),    13 kB    (1.59%),  
       System.Diagnostics.PerformanceCounter [] System.Collections.Generic.List<T>->System.Diagnostics.PerformanceCounter []->(System.Diagnostics.PerformanceCounter):	  12 kB    (1.53%)  (25 objects,  1.6 kB    (0.20%))
         Previous allocations (newest to oldest):   12 kB    (1.53%),    12 kB    (1.53%),    12 kB    (1.53%),  
        System.Diagnostics.PerformanceCounterLib System.Collections.Hashtable.bucket []->System.Diagnostics.PerformanceCounterLib->(System.Collections.Hashtable,System.Diagnostics.PerformanceMonitor,System.String,...):	 358 kB    (45.05%)  (1 object,   96 bytes (0.01%))
          Previous allocations (newest to oldest):  358 kB    (45.05%),   358 kB    (45.05%),   358 kB    (45.05%),  
        System.Configuration.FactoryRecord System.Collections.Hashtable.bucket []->System.Configuration.FactoryRecord->(System.String):	  62 kB    (7.84%)  (116 objects,   12 kB    (1.48%))
          Previous allocations (newest to oldest):   62 kB    (7.84%),    62 kB    (7.84%),    62 kB    (7.84%),  
        System.Text.RegularExpressions.RegexInterpreter System.Text.RegularExpressions.ExclusiveReference->System.Text.RegularExpressions.RegexInterpreter->(System.Int32 [],System.String,System.Text.RegularExpressions.Match,...):	  15 kB    (1.84%)  (15 objects,  2.3 kB    (0.30%))
          Previous allocations (newest to oldest):   15 kB    (1.84%),    15 kB    (1.84%),    15 kB    (1.84%),  
        System.Diagnostics.PerformanceCounter System.Diagnostics.PerformanceCounter []->System.Diagnostics.PerformanceCounter->(System.String):	  11 kB    (1.33%)  (52 objects,  8.9 kB    (1.13%))
          Previous allocations (newest to oldest):   11 kB    (1.33%),    11 kB    (1.33%),    11 kB    (1.33%),  
        System.Collections.Hashtable.bucket [] System.Collections.Hashtable->System.Collections.Hashtable.bucket []->(System.RuntimeType):	 9.4 kB    (1.18%)  (7 objects,  2.7 kB    (0.34%))
          Previous allocations (newest to oldest):  9.4 kB    (1.18%),   9.4 kB    (1.18%),   9.4 kB    (1.18%),  
        System.Text.RegularExpressions.RegexBoyerMoore System.Text.RegularExpressions.RegexCode->System.Text.RegularExpressions.RegexBoyerMoore->(System.Int32 [],System.String):	 8.6 kB    (1.09%)  (13 objects,  936 bytes (0.12%))
          Previous allocations (newest to oldest):  8.6 kB    (1.09%),   8.6 kB    (1.09%),   8.6 kB    (1.09%),  
        System.Configuration.SectionRecord System.Collections.Hashtable.bucket []->System.Configuration.SectionRecord->(System.Net.Configuration.SettingsSection,System.String):	 8.6 kB    (1.08%)  (2 objects,  144 bytes (0.02%))
          Previous allocations (newest to oldest):  8.6 kB    (1.08%),   8.6 kB    (1.08%),   8.6 kB    (1.08%),  
         System.Collections.Hashtable System.Diagnostics.PerformanceCounterLib->System.Collections.Hashtable->(System.Collections.Hashtable.bucket []):	 358 kB    (45.01%)  (2 objects,  176 bytes (0.02%))
           Previous allocations (newest to oldest):  358 kB    (45.01%),   358 kB    (45.01%),   358 kB    (45.01%),  
         System.Configuration.RuntimeConfigurationRecord.RuntimeConfigurationFactory System.Configuration.FactoryRecord->System.Configuration.RuntimeConfigurationRecord.RuntimeConfigurationFactory->(System.Reflection.RuntimeConstructorInfo):	  14 kB    (1.81%)  (3 objects,   96 bytes (0.01%))
           Previous allocations (newest to oldest):   14 kB    (1.81%),    14 kB    (1.81%),    14 kB    (1.81%),  
         System.Net.Configuration.SettingsSection System.Configuration.SectionRecord->System.Net.Configuration.SettingsSection->(System.Configuration.ConfigurationPropertyCollection,System.Configuration.ConfigurationValues,System.Configuration.RuntimeConfigurationRecord,...):	 8.5 kB    (1.07%)  (1 object,  184 bytes (0.02%))
           Previous allocations (newest to oldest):  8.5 kB    (1.07%),   8.5 kB    (1.07%),   8.5 kB    (1.07%),  
          System.Collections.Hashtable.bucket [] System.Collections.Hashtable->System.Collections.Hashtable.bucket []->(System.Int32):	 328 kB    (41.30%)  (4 objects,   95 kB    (12.00%))
            Previous allocations (newest to oldest):  328 kB    (41.30%),   328 kB    (41.30%),   328 kB    (41.30%),  
          System.Reflection.RuntimeConstructorInfo System.Configuration.RuntimeConfigurationRecord.RuntimeConfigurationFactory->System.Reflection.RuntimeConstructorInfo->(System.Reflection.ParameterInfo [],System.RuntimeType):	  14 kB    (1.80%)  (3 objects,  336 bytes (0.04%))
            Previous allocations (newest to oldest):   14 kB    (1.80%),    14 kB    (1.80%),    14 kB    (1.80%),  
           System.Collections.ArrayList System.Configuration.ConfigurationValues->System.Collections.ArrayList->(System.Object []):	  50 kB    (6.28%)  (11 objects,  440 bytes (0.05%))
             Previous allocations (newest to oldest):   50 kB    (6.28%),    50 kB    (6.28%),    50 kB    (6.28%),  
           System.RuntimeType.RuntimeTypeCache System.Reflection.RuntimeConstructorInfo->System.RuntimeType.RuntimeTypeCache->(System.RuntimeType,System.RuntimeType.RuntimeTypeCache.MemberInfoCache<T>):	  13 kB    (1.62%)  (1 object,  136 bytes (0.02%))
             Previous allocations (newest to oldest):   13 kB    (1.62%),    13 kB    (1.62%),    13 kB    (1.62%),  
            System.Object [] System.Collections.ArrayList->System.Object []->(System.Collections.Specialized.NameObjectCollectionBase.NameObjectEntry):	  49 kB    (6.23%)  (3 objects,  320 bytes (0.04%))
              Previous allocations (newest to oldest):   49 kB    (6.23%),    49 kB    (6.23%),    49 kB    (6.23%),  
            System.RuntimeType.RuntimeTypeCache.MemberInfoCache<T> System.RuntimeType.RuntimeTypeCache->System.RuntimeType.RuntimeTypeCache.MemberInfoCache<T>->(System.Reflection.CerArrayList<T>):	  13 kB    (1.67%)  (6 objects,  336 bytes (0.04%))
              Previous allocations (newest to oldest):   13 kB    (1.67%),    13 kB    (1.67%),    13 kB    (1.67%),  
             System.Collections.Specialized.NameObjectCollectionBase.NameObjectEntry System.Object []->System.Collections.Specialized.NameObjectCollectionBase.NameObjectEntry->(System.String):	  49 kB    (6.19%)  (19 objects,  608 bytes (0.07%))
               Previous allocations (newest to oldest):   49 kB    (6.19%),    49 kB    (6.19%),    49 kB    (6.19%),  
              System.Configuration.ConfigurationValue System.Collections.Specialized.NameObjectCollectionBase.NameObjectEntry->System.Configuration.ConfigurationValue->(Crypton.Carbonator.Config.PerformanceCounterCollection):	  38 kB    (4.74%)  (1 object,   40 bytes (0.00%))
                Previous allocations (newest to oldest):   38 kB    (4.74%),    38 kB    (4.74%),    38 kB    (4.74%),  
               Crypton.Carbonator.Config.PerformanceCounterCollection System.Configuration.ConfigurationValue->Crypton.Carbonator.Config.PerformanceCounterCollection->(System.Collections.ArrayList,System.Configuration.ConfigurationElementProperty,System.Configuration.ConfigurationValues,...):	  38 kB    (4.73%)  (1 object,  168 bytes (0.02%))
                 Previous allocations (newest to oldest):   38 kB    (4.73%),    38 kB    (4.73%),    38 kB    (4.73%),  
                System.Collections.ArrayList Crypton.Carbonator.Config.PerformanceCounterCollection->System.Collections.ArrayList->(System.Object []):	  37 kB    (4.64%)  (1 object,   40 bytes (0.00%))
                  Previous allocations (newest to oldest):   37 kB    (4.64%),    37 kB    (4.64%),    37 kB    (4.64%),  
                 System.Object [] System.Collections.ArrayList->System.Object []->(System.Configuration.ConfigurationElementCollection.Entry):	  38 kB    (4.77%)  (2 objects,  352 bytes (0.04%))
                   Previous allocations (newest to oldest):   38 kB    (4.77%),    38 kB    (4.77%),    38 kB    (4.77%),  
                  System.Configuration.ConfigurationElementCollection.Entry System.Object []->System.Configuration.ConfigurationElementCollection.Entry->(System.String):	  38 kB    (4.73%)  (26 objects,  1.0 kB    (0.13%))
                    Previous allocations (newest to oldest):   38 kB    (4.73%),    38 kB    (4.73%),    38 kB    (4.73%),  
                   Crypton.Carbonator.Config.PerformanceCounterElement System.Configuration.ConfigurationElementCollection.Entry->Crypton.Carbonator.Config.PerformanceCounterElement->(System.Configuration.ConfigurationElementProperty,System.Configuration.ConfigurationValues):	  36 kB    (4.47%)  (25 objects,  2.7 kB    (0.34%))
                     Previous allocations (newest to oldest):   36 kB    (4.47%),    36 kB    (4.47%),    36 kB    (4.47%),  
                    System.Configuration.ConfigurationValues Crypton.Carbonator.Config.PerformanceCounterElement->System.Configuration.ConfigurationValues->(System.Collections.ArrayList,System.Collections.Hashtable):	  33 kB    (4.13%)  (25 objects,  2.1 kB    (0.27%))
                      Previous allocations (newest to oldest):   33 kB    (4.13%),    33 kB    (4.13%),    33 kB    (4.13%),  
                     System.Collections.ArrayList(1) System.Configuration.ConfigurationValues->System.Collections.ArrayList->(System.Object []):	  21 kB    (2.61%)  (36 objects,  1.4 kB    (0.18%))
                       Previous allocations (newest to oldest):   21 kB    (2.61%),    21 kB    (2.61%),    21 kB    (2.61%),  
                     System.Collections.Hashtable System.Configuration.ConfigurationValues->System.Collections.Hashtable->(System.Collections.Hashtable.bucket []):	  18 kB    (2.32%)  (49 objects,  4.2 kB    (0.53%))
                       Previous allocations (newest to oldest):   18 kB    (2.32%),    18 kB    (2.32%),    18 kB    (2.32%),  
                      System.Collections.Hashtable.bucket [](1) System.Collections.Hashtable->System.Collections.Hashtable.bucket []->(System.String):	  30 kB    (3.82%)  (3 objects,  3.6 kB    (0.45%))
                        Previous allocations (newest to oldest):   30 kB    (3.82%),    30 kB    (3.82%),    30 kB    (3.82%),  
                      System.Object [](1) System.Collections.ArrayList->System.Object []->(System.Collections.Specialized.NameObjectCollectionBase.NameObjectEntry):	  19 kB    (2.43%)  (28 objects,  2.5 kB    (0.32%))
                        Previous allocations (newest to oldest):   19 kB    (2.43%),    19 kB    (2.43%),    19 kB    (2.43%),  
                       System.Diagnostics.CategoryEntry System.Collections.Hashtable.bucket []->System.Diagnostics.CategoryEntry->(System.Int32 []):	  22 kB    (2.81%)  (81 objects,  3.2 kB    (0.40%))
                         Previous allocations (newest to oldest):   22 kB    (2.81%),    22 kB    (2.81%),    22 kB    (2.81%),  
                       System.Collections.Specialized.NameObjectCollectionBase.NameObjectEntry(1) System.Object []->System.Collections.Specialized.NameObjectCollectionBase.NameObjectEntry->(System.String):	  17 kB    (2.12%)  (157 objects,  4.9 kB    (0.62%))
                         Previous allocations (newest to oldest):   17 kB    (2.12%),    17 kB    (2.12%),    17 kB    (2.12%),  
                          System.String System.Collections.Hashtable.bucket []->System.String:	 190 kB    (23.96%)  (2577 objects,  190 kB    (23.96%))
                            Previous allocations (newest to oldest):  190 kB    (23.96%),   192 kB    (24.12%),   191 kB    (24.09%),  
                          System.String System.Object []->System.String:	  63 kB    (7.94%)  (1270 objects,   63 kB    (7.94%))
                            Previous allocations (newest to oldest):   63 kB    (7.94%),    64 kB    (8.11%),    64 kB    (8.07%),  
                          System.Int32 System.Collections.Hashtable.bucket []->System.Int32:	  57 kB    (7.22%)  (2447 objects,   57 kB    (7.22%))
                            Previous allocations (newest to oldest):   57 kB    (7.22%),    57 kB    (7.22%),    57 kB    (7.22%),  
                          System.String System.Configuration.FactoryRecord->System.String:	  36 kB    (4.55%)  (196 objects,   36 kB    (4.55%))
                            Previous allocations (newest to oldest):   36 kB    (4.55%),    36 kB    (4.55%),    36 kB    (4.55%),  
                          System.Int32 [] System.Diagnostics.CategoryEntry->System.Int32 []:	  19 kB    (2.41%)  (162 objects,   19 kB    (2.41%))
                            Previous allocations (newest to oldest):   19 kB    (2.41%),    19 kB    (2.41%),    19 kB    (2.41%),  
                          System.RuntimeType System.Object []->System.RuntimeType:	  11 kB    (1.35%)  (228 objects,   11 kB    (1.35%))
                            Previous allocations (newest to oldest):   11 kB    (1.35%),    11 kB    (1.35%),    11 kB    (1.35%),
